"""empty message

Revision ID: 2853d7bd79b5
Revises: fa52951df617
Create Date: 2023-06-30 16:51:34.400576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2853d7bd79b5'
down_revision = 'fa52951df617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.String(length=100000), nullable=False))

    with op.batch_alter_table('historial_pedidos', schema=None) as batch_op:
        batch_op.alter_column('precioActual',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('historial_pedidos', schema=None) as batch_op:
        batch_op.alter_column('precioActual',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
