"""empty message

Revision ID: 6cc7ee451d05
Revises: 
Create Date: 2023-06-30 16:59:46.480246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc7ee451d05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_comida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipoComida', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=70), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('nacimiento', sa.DateTime(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('cif', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reserva', sa.Boolean(), nullable=False),
    sa.Column('delivery', sa.Boolean(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=10000000), nullable=True),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('idEmpresa', sa.Integer(), nullable=False),
    sa.Column('idPago', sa.String(length=50), nullable=False),
    sa.Column('delivery', sa.Boolean(), nullable=False),
    sa.Column('hora', sa.DateTime(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('idEmpresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios_empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mañana', sa.Boolean(), nullable=False),
    sa.Column('tarde', sa.Boolean(), nullable=False),
    sa.Column('idEmpresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=240), nullable=False),
    sa.Column('precio', sa.Float(precision=2), nullable=True),
    sa.Column('idEmpresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reseñas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=False),
    sa.Column('idEmpresa', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('reseña', sa.String(length=240), nullable=False),
    sa.Column('hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_comida_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idEmpresa', sa.Integer(), nullable=False),
    sa.Column('idTipoComida', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['idTipoComida'], ['tipo_comida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idFactura', sa.Integer(), nullable=False),
    sa.Column('idProducto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precioActual', sa.Float(precision=2), nullable=True),
    sa.ForeignKeyConstraint(['idFactura'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_pedidos')
    op.drop_table('tipo_comida_empresa')
    op.drop_table('reseñas')
    op.drop_table('productos')
    op.drop_table('horarios_empresas')
    op.drop_table('favoritos')
    op.drop_table('factura')
    op.drop_table('empresa')
    op.drop_table('cliente')
    op.drop_table('usuario')
    op.drop_table('tipo_comida')
    # ### end Alembic commands ###
